#!/usr/bin/php
<?php

use Blockchain\Network\HttpServer;
use Blockchain\Network\WebSocket;
use Workerman\Worker;

require_once __DIR__ . '/bootstrap.php';

$argv_http     = explode(":", isset($argv[2]) ? $argv[2] : "");
$http_port     = !empty($argv_http[0]) ? $argv_http[0] : 8000;
$http_nprocess = !empty($argv_http[1]) ? $argv_http[1] : 4;

$argv_ws     = explode(":", isset($argv[3]) ? $argv[3] : "");
$ws_port     = !empty($argv_ws[0]) ? $argv_ws[0] : 2210;
$ws_nprocess = !empty($argv_ws[1]) ? $argv_ws[1] : 4;

new Channel\Server();

new Blockchain\Server();

new HttpServer($app, "0.0.0.0", $http_port, $http_nprocess);

$ws = new WebSocket("0.0.0.0", $ws_port, $ws_nprocess);
$ws->setAddress("127.0.0.1:" . $ws_port);

if (isset($argv[4])) {
    foreach (explode(",", $argv[4]) as $peer) {
        $ws->setPeerConnect($peer);
    }
}

Worker::runAll();