#!/usr/bin/php
<?php

use Blockchain\Network\HttpServer;
use Blockchain\Network\WebSocket;
use Blockchain\Network\WebSocketConnection;
use Workerman\Worker;

require_once __DIR__ . '/bootstrap.php';

$GLOBALS["proccess_qtd"] = 4;

new Channel\Server();

new HttpServer($app, "0.0.0.0", !empty($argv[2]) ? $argv[2] : 80);

$ws = new WebSocket("0.0.0.0", !empty($argv[3]) ? $argv[3] : 2346, $GLOBALS["proccess_qtd"]);

$ws->onConnect(function (WebSocketConnection $connection) use ($ws) {
    echo "Foi, conectou alguem ai\n";
    
    $connection->send(["Vai para você 1"]);
});

$ws->onMessage(function (WebSocketConnection $connection, $data) use ($ws) {
    //    if (is_object($data) && $data->type == "connectaai") {
    //        $ws->connect("127.0.0.1", "2348");
    //    }
    var_dump($data);
    
    //    $connection->send(["message" => "ok"]);
});

$ws->onStart(function () use ($ws) {
    Channel\Client::connect();
    
    Channel\Client::on("sendAll", function($event_data) use ($ws) {
        $ws->sendAll($event_data);
    });
    
    Channel\Client::on("connect", function($event_data) use ($ws) {
        $ws->connect($event_data[0], $event_data[1]);
    });
});

Worker::runAll();