#!/usr/bin/php
<?php

use Blockchain\Network\HttpServer;
use Blockchain\Network\WebSocket;
use Workerman\Worker;

require_once __DIR__ . '/bootstrap.php';

$GLOBALS["proccess_qtd"] = 4;

new Channel\Server();

new GlobalData\Server();

new HttpServer($app, "0.0.0.0", !empty($argv[2]) ? $argv[2] : 80);

new WebSocket("0.0.0.0", !empty($argv[3]) ? $argv[3] : 2346, $GLOBALS["proccess_qtd"]);

Worker::runAll();